### PR TITLE
Add JDK 17 docker image

### PR DESCRIPTION
**Pull request by ajsutton**
## PR Description
Adds a JDK 17 docker image.
Remove JDK 14 and 15 images as those JVMs are no longer supported by upstream providers.

JDK 16 remains the default docker image for now.

## Documentation

- [x] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by tbenr** [comment]
shouldn't we remove `docker/jdk14` and `docker/jdk15` dirs since we are deprecating those versions?

**Review by tbenr — APPROVED** [review]
LGTM. just look at the comment above in regards of deprecated jdks

**Comment by ajsutton** [comment]
> shouldn't we remove `docker/jdk14` and `docker/jdk15` dirs since we are deprecating those versions?

Ah yes, good spot.

**Review by rolfyone — APPROVED** [review]
LGTM

**Pull request merged**
