### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tbenr**
There is also rocksdbjni major release 7.x.x (not even tried)

I opened an issue about Javalin 4->5 migration
 
## Documentation

- [ ] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Review by mehdi-aouadi — APPROVED** [review]

**Comment by tbenr** [comment]
image
🤔

**Comment by zilm13** [comment]
I finally remembered what's that
it comes from unmigrated api and it's a part of `javalin-openapi`
https://github.com/javalin/javalin-openapi/blob/main/javalin-swagger-plugin/src/main/kotlin/io/javalin/openapi/plugin/swagger/SwaggerHandler.kt#L26-L74
so until removing old api our version of swagger must match the one used in `javalin-openapi`

**Comment by ajsutton** [comment]
Errorprone seem to be disabling `CanIgnoreReturnValueSuggester` by default again (https://github.com/google/error-prone/issues/3366) so definitely something we could just turn off in our build config - we already enable and disable various errorprone rules to suit our needs.

**Comment by tbenr** [comment]
The new errorprone spotted a nice one

**Pull request merged**
