### PR TITLE
support `on_block` and `on_merge_block` fork_choice tests

### PR DESCRIPTION
**Pull request by tbenr**
begin the work for supporting `on_block` and `on_merge_block` fork_choice tests

## Documentation

- [ ] I thought about documentation and added the `documentation` label to this PR if updates are required.

## Changelog

- [ ] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by hwwhww** [comment]
Hi @tbenr,
Just noticed that Teku is going to support `on_merge_block`  👍👍
Two quick questions and notes:
1. I'm working on a more complete test format: https://github.com/ethereum/consensus-specs/pull/2639. Do you think it would be easier to integrate into Teku?
2. I think @ajsutton set `on_block` tests to `IGNORE_TESTS` because one single test case triggered Teku's protoarray implementation issue. The edge case condition requires >1/3 slashings, and thus it is low-priority. So I guess it might still having problem if you enable it now. Or @ajsutton can correct me if that issue has been fixed?

**Comment by ajsutton** [comment]
> 2. I think @ajsutton set `on_block` tests to `IGNORE_TESTS` because one single test case triggered Teku's protoarray implementation issue. The edge case condition requires >1/3 slashings, and thus it is low-priority. So I guess it might still having problem if you enable it now. Or @ajsutton can correct me if that issue has been fixed?

Yeah we will likely have to disable that one test.  Would be good to get all the others running on master anyway.

**Comment by tbenr** [comment]
Hi @hwwhww 

> 1. I'm working on a more complete test format: [Mock Engine API req/resp in tests - take 2 ethereum/consensus-specs#2639](https://github.com/ethereum/consensus-specs/pull/2639). Do you think it would be easier to integrate into Teku?

I had a quick look and the new proposed seems to have more expressiveness. I don't see any particular problem to support it, but one question:
why on `get_pow_block` you are accepting an array as input? shouldn't be only the blockhash the consensus layer is looking up?

> 2. I think @ajsutton set `on_block` tests to `IGNORE_TESTS` because one single test case triggered Teku's protoarray implementation issue. The edge case condition requires >1/3 slashings, and thus it is low-priority. So I guess it might still having problem if you enable it now. Or @ajsutton can correct me if that issue has been fixed?

This pr is my attempt to activate more tests as possible. As @ajsutton confirmed, we will probabily end up disabling one of them. could make sense to move from IgnoreAll to IgnoreOne in main branch first

**Comment by hwwhww** [comment]
@tbenr 
> why on get_pow_block you are accepting an array as input? shouldn't be only the blockhash the consensus layer is looking up?

You're right. I just fixed it in the PR. Thank you!

**Comment by ajsutton** [comment]
Going to close this one. We've got fork choice on_block tests already enabled in master and #4597 gets the on_merge_block tests passing on master as well.

**Pull request closed without merging**
