### PR TITLE
Building Experimental Light Client for Teku

### PR DESCRIPTION
**Pull request by jeyakatsa**
## PR Description

Currently in the process of building the Light Client Experimental Server infrastructure into Teku as suggested by @benjaminion here: https://github.com/ConsenSys/teku/issues/4230

If the code is too early in the process to merge as a pull request, I'll be working on this for the next 3-4 months so I can open a new pull request once more logic has been developed.

### CODE REVIEW

**Comment by ajsutton** [comment]
Awesome. I think it's definitely worth merging things in small steps rather than a Big Bang at the end - makes reviewing stuff a lot easier.  This might be a bit soon as I can't quite work out what these empty classes are aiming to do. And the build has some failures - looks like a compilation failure and you need to run `./gradlew spotlessApply` to apply our formatting rules.

A couple of things we look for in finding a split point to merge work in:

1. It needs to be toggled off. We often use hidden `--X` flags to control these toggles so new functionality is off by default but can be easily enabled for testing.  You can run `teku -X` to see the existing hidden options to help find examples in the code
2. We aim to make each piece logically complete, even if it's only a small piece of the solution.  Ideally it would be a small "vertical" slice so we can see it actually work though it may only get one step through the process.  For example adding just the external definition of a REST API endpoint (only added if the toggle is enabled) so that we can see the Api definition turn up in the OpenAPI docs but there may be no actual implementation behind it so it always returns a server error or an empty response.  It's not always possible to find small steps that are each externally visible but that's the aim because then you can test as you go and see it gradually get further along. Whereas if you start in the middle you may wind up building out a lot of stuff before you can start to use it at all and then discover it doesn't actually work in practice.
3. Each piece added needs to be production ready and tested. Production ready doesn't mean the whole feature is complete but the code that does exist is at a high standard, well defined, tested etc.

**Comment by jeyakatsa** [comment]
Will do. Will check up on all this tomorrow and update as time goes by (will open a new pull request once an entire class is built with `./gradlew spotlessApply` implemented etc) thanks for the feedback @ajsutton !

**Comment by jeyakatsa** [comment]
@ajsutton Hi Adrian, I'm about to resume building the light-client. I've successfully implemented a `./gradlew spotlessApply` build to the Teku client, but it still has compilation issues in regards to the dependencies...

And as far as testing my light-client build, all the compilation issues will have to be resolved first right?

Because I tried a mass `./gradlew` implementation to resolve the compilation issues but ran into Build failures at 40%... Are y'all running into Build failures with the `./gradlew` implementation?

I'll continue trying to build the API functionality at least until these dependency/compilation issues can be resolved (LMK[Let Me Know]).

Thanks.

**Comment by ajsutton** [comment]
> And as far as testing my light-client build, all the compilation issues will have to be resolved first right?

Yep, if we can't compile cleanly we pretty much can't do anything.


> Because I tried a mass `./gradlew` implementation to resolve the compilation issues but ran into Build failures at 40%... Are y'all running into Build failures with the `./gradlew` implementation?

We're not having any issues with building.  CI runs that process on every PR and every merge to master so we always know it works.  I'd have to see the errors your getting from gradle to know why it's having issues but you'd expect it to fail if there are compilation problems.

You can do just the compile step with:
```
./gradlew compileJava compileTestJava compileJmhJava compileIntegrationTestJava compileAcceptanceTestJava
```
which may make it easier to track down the compilation issue at least.

**Comment by jeyakatsa** [comment]
> You can do just the compile step with:
> 
> ```
> ./gradlew compileJava compileTestJava compileJmhJava compileIntegrationTestJava compileAcceptanceTestJava
> ```
> 
> which may make it easier to track down the compilation issue at least.

Thanks, will try that. 

If I continue running into any compilation errors I'll try resolving them by myself first (in order to sharpen my problem solving skills) for a few hours and open an issue or get back to you if I need further help.

Thanks again AJ.

**Comment by jeyakatsa** [comment]
@ajsutton Update:

Good News: I got the gradle build compiler up to 99% executed. 

Bad News: Build failing at 99%.

Will return tomorrow to see if I can successfully complete the build.

**Comment by jeyakatsa** [comment]
@ajsutton 

When I run `./gradlew spotlessApply` & `./gradlew distTar installDist` it completes successfully at 100%, but when I run `./gradlew`, it fails at 99%. 

I narrowed it down and its failing at these points:

 ```
Eth2P2PNetworkOptionsTest > helpDisplaysDefaultNetwork() FAILED
    java.lang.AssertionError at Eth2P2PNetworkOptionsTest.java:134
```
`tech.pegasys.teku.cli.options.LoggingOptionsTest`

`tech.pegasys.teku.cli.subcommand`

I wonder maybe if I need to reinstall my gradle? I've already deleted and re-pulled the teku repo into my local folder.

Will continue chipping away at this issue.

**Comment by ajsutton** [comment]
> ```
> Eth2P2PNetworkOptionsTest > helpDisplaysDefaultNetwork() FAILED
>    java.lang.AssertionError at Eth2P2PNetworkOptionsTest.java:134
> ```

It should provide a URL to a HTML page that will give more detail on why those tests failed.  It's probably `teku/build/reports/tests/test/index.html` that you want to open but the gradle output will have it as a full URL that will definitely be right.

**Comment by jeyakatsa** [comment]
Yup, checked that html page, that's how I narrowed down the errors to these classes:

`tech.pegasys.teku.cli.options.LoggingOptionsTest`

`tech.pegasys.teku.cli.subcommand`

I'll continue chipping away at this issue... I'm hoping I can start building (and testing) at least some of the light client API (without some of the dependencies running).

I'll figure out something.

**Comment by ajsutton** [comment]
The HTML should provide complete details of the failure (including a stack trace).  If you can share that I can help identify what's failing. It may be the test makes some assumption about the system which isn't true in your case and the test just needs fixing.

**Comment by jeyakatsa** [comment]
Unsure if this is what you need, but within the _tech.pegasys.teku.cli.options package_, _Eth2P2PNetworkOptionsTest_ class, the _helpDisplaysDefaultNetwork()_ failure results are showing:

```
java.lang.AssertionError: 
Expecting:
 <"
?[1mteku?[21m?[0m [OPTIONS] [COMMAND]

Description:

Run the Teku beacon chain client and validator

Options:
  ?[33m-c?[39m?[0m, ?[33m--config-file?[39m?[0m=?[3m<FILENAM?[23m?[0m?[3mE>?[23m?[0m
                             Path/filename of the yaml config file (default:
                               none)
      ?[33m--data-beacon-path?[39m?[0m=?[3m<FI?[23m?[0m?[3mLENAME>?[23m?[0m
                             Path to beacon node data
                               Default: <data-base-path>/beacon
      ?[33m--data-path, --data-ba?[39m?[0m?[33mse-path?[39m?[0m=?[3m<FILENAME>?[23m?[0m
                             Path to the base directory for storage
                               Default: C:\Users\Jeyak\AppData\Local\teku
      ?[33m--data-storage-archive?[39m?[0m?[33m-frequency?[39m?[0m=?[3m<FREQUENCY>?[23m?[0m
                             Sets the frequency, in slots, at which to store
                               finalized states to disk. This option is ignored
                               if --data-storage-mode is set to PRUNE
                               Default: 2048
      ?[33m--data-storage-mode?[39m?[0m=?[3m<S?[23m?[0m?[3mTORAGE_MODE>?[23m?[0m
                             Sets the strategy for handling historical chain
                               data.  (Valid values: ARCHIVE, PRUNE)
                               Default: PRUNE
      ?[33m--data-storage-non-can?[39m?[0m?[33monical-blocks-enabled?[39m?[0m[=?[3m<BOOLEAN>?[23m?[0m]
                             Store non-canonical blocks
                               Default: false
      ?[33m--data-validator-path?[39m?[0m=?[3m<FILENAME>?[23m?[0m
                             Path to validator client data
                               Default: <data-base-path>/validator
      ?[33m--eth1-deposit-contrac?[39m?[0m?[33mt-address?[39m?[0m=?[3m<ADDRESS>?[23m?[0m
                             Contract address for the deposit contract. Only
                               required when creating a custom network.
      ?[33m--eth1-deposit-contrac?[39m?[0m?[33mt-max-request-size?[39m?[0m=?[3m<INTEGER>?[23m?[0m
                             Maximum number of blocks to request deposit
                               contract event logs for in a single request.
                               Default: 10000
      ?[33m--eth1-endpoint, --eth?[39m?[0m?[33m1-endpoints?[39m?[0m=?[3m<NETWORK>?[23m?[0m[,?[3m<NETWORK>?[23m?[0m...]...
                             URLs for Eth1 nodes.
                               Default: []
  ?[33m-h?[39m?[0m, ?[33m--help?[39m?[0m                 Show this help message and exit.
      ?[33m--initial-state?[39m?[0m=?[3m<STRIN?[23m?[0m?[3mG>?[23m?[0m
                             The initial state. This value should be a file or
                               URL pointing to an SSZ-encoded finalized
                               checkpoint state.
  ?[33m-l?[39m?[0m, ?[33m--logging?[39m?[0m=?[3m<LOG VERBOSI?[23m?[0m?[3mTY LEVEL>?[23m?[0m
                             Logging verbosity levels: OFF, FATAL, ERROR, WARN,
                               INFO, DEBUG, TRACE, ALL (default: INFO).
      ?[33m--log-color-enabled?[39m?[0m[=?[3m<?[23m?[0m?[3mBOOLEAN>?[23m?[0m]
                             Whether Status and Event log messages include a
                               console color display code
                               Default: true
      ?[33m--log-destination?[39m?[0m=?[3m<LOG?[23m?[0m?[3m_DESTINATION>?[23m?[0m
                             Whether a logger is added for the console, the log
                               file, or both (Valid values: BOTH, CONSOLE,
                               DEFAULT_BOTH, FILE)
                               Default: DEFAULT_BOTH
      ?[33m--log-file?[39m?[0m=?[3m<FILENAME>?[23m?[0m  Path containing the location (relative or
                               absolute) and the log filename. If not set will
                               default to <data-path>/logs/teku.log
      ?[33m--log-file-name-patter?[39m?[0m?[33mn?[39m?[0m=?[3m<REGEX>?[23m?[0m
                             Pattern for the filename to apply to rolled over
                               log files. If not set will default to
                               <data-path>/logs/teku_%d{yyyy-MM-dd}.log
      ?[33m--log-include-events-e?[39m?[0m?[33mnabled?[39m?[0m[=?[3m<BOOLEAN>?[23m?[0m]
                             Whether frequent update events are logged (e.g.
                               every slot and epoch event)
                               Default: true
      ?[33m--log-include-validato?[39m?[0m?[33mr-duties-enabled?[39m?[0m[=?[3m<BOOLEAN>?[23m?[0m]
                             Whether events are logged when validators perform
                               duties
                               Default: true
      ?[33m--metrics-categories?[39m?[0m[=?[3m<METRICS_CATEGORY>?[23m?[0m[,?[3m<METRICS_CATEGORY>?[23m?[0m...]...]
                             Metric categories to enable
                               Default: [JVM, PROCESS, BEACON, DISCOVERY,
                               EVENTBUS, EXECUTOR, LIBP2P, NETWORK, STORAGE,
                               STORAGE_HOT_DB, STORAGE_FINALIZED_DB,
                               REMOTE_VALIDATOR, VALIDATOR,
                               VALIDATOR_PERFORMANCE]
      ?[33m--metrics-enabled?[39m?[0m[=?[3m<BO?[23m?[0m?[3mOLEAN>?[23m?[0m]
                             Enables metrics collection via Prometheus
                               Default: false
      ?[33m--metrics-host-allowli?[39m?[0m?[33mst?[39m?[0m[=?[3m<hostname>?[23m?[0m[,?[3m<hostname>?[23m?[0m...]...]
                             Comma-separated list of hostnames to allow, or *
                               to allow any host
                               Default: [127.0.0.1, localhost]
      ?[33m--metrics-interface?[39m?[0m=?[3m<N?[23m?[0m?[3mETWORK>?[23m?[0m
                             Metrics network interface to expose metrics for
                               Prometheus
                               Default: 127.0.0.1
      ?[33m--metrics-port?[39m?[0m=?[3m<INTEGE?[23m?[0m?[3mR>?[23m?[0m
                             Metrics port to expose metrics for Prometheus
                               Default: 8008
  ?[33m-n?[39m?[0m, ?[33m--network?[39m?[0m=?[3m<NETWORK>?[23m?[0m    Represents which network to use.
                               Default: mainnet
      ?[33m--p2p-advertised-ip?[39m?[0m=?[3m<N?[23m?[0m?[3mETWORK>?[23m?[0m
                             P2P advertised IP (Default: 127.0.0.1)
      ?[33m--p2p-advertised-port?[39m?[0m=?[3m<INTEGER>?[23m?[0m
                             P2P advertised port. The default is the port
                               specified in --p2p-port
      ?[33m--p2p-advertised-udp-p?[39m?[0m?[33mort?[39m?[0m=?[3m<INTEGER>?[23m?[0m
                             Advertised UDP port to external peers. The default
                               is the port specified in --p2p-advertised-port
      ?[33m--p2p-discovery-bootno?[39m?[0m?[33mdes?[39m?[0m[=?[3m<enr:-...>?[23m?[0m[,?[3m<enr:-...>?[23m?[0m...]...]
                             List of ENRs of the bootnodes
      ?[33m--p2p-discovery-enable?[39m?[0m?[33md?[39m?[0m[=?[3m<BOOLEAN>?[23m?[0m]
                             Enables discv5 discovery
                               Default: true
      ?[33m--p2p-enabled?[39m?[0m[=?[3m<BOOLEA?[23m?[0m?[3mN>?[23m?[0m]
                             Enables P2P
                               Default: true
      ?[33m--p2p-interface?[39m?[0m=?[3m<NETWO?[23m?[0m?[3mRK>?[23m?[0m
                             P2P network interface
                               Default: 0.0.0.0
      ?[33m--p2p-nat-method?[39m?[0m=?[3m<natM?[23m?[0m?[3method>?[23m?[0m
                             Specify the NAT circumvention method to be used,
                               possible values are UPNP, NONE. NONE will
                               require manual router configuration.
                               Default: NONE
      ?[33m--p2p-peer-lower-bound?[39m?[0m=?[3m<INTEGER>?[23m?[0m
                             Lower bound on the target number of peers
                               Default: 64
      ?[33m--p2p-peer-upper-bound?[39m?[0m=?[3m<INTEGER>?[23m?[0m
                             Upper bound on the target number of peers
                               Default: 74
      ?[33m--p2p-port?[39m?[0m=?[3m<INTEGER>?[23m?[0m   P2P port
                               Default: 9000
      ?[33m--p2p-private-key-file?[39m?[0m=?[3m<FILENAME>?[23m?[0m
                             This node's private key file. If not specified,
                               uses or generates a key which is stored within
                               the <beacon-data-dir>.
      ?[33m--p2p-static-peers?[39m?[0m[=?[3m<P?[23m?[0m?[3mEER_ADDRESSES>?[23m?[0m[,?[3m<PEER_ADDRESSES>?[23m?[0m...]...]
                             Static peers
                               Default: []
      ?[33m--p2p-subscribe-all-su?[39m?[0m?[33mbnets-enabled?[39m?[0m[=?[3m<BOOLEAN>?[23m?[0m]
                               Default: false
      ?[33m--p2p-udp-port?[39m?[0m=?[3m<INTEGE?[23m?[0m?[3mR>?[23m?[0m
                             UDP port used for discovery. The default is the
                               port specified in --p2p-port
      ?[33m--rest-api-cors-origin?[39m?[0m?[33ms?[39m?[0m[=?[3m<origin>?[23m?[0m[,?[3m<origin>?[23m?[0m...]...]
                             Comma separated list of origins to allow, or * to
                               allow any origin
                               Default: []
      ?[33m--rest-api-docs-enable?[39m?[0m?[33md?[39m?[0m[=?[3m<BOOLEAN>?[23m?[0m]
                             Enable swagger-docs and swagger-ui endpoints
                               Default: false
      ?[33m--rest-api-enabled?[39m?[0m[=?[3m<B?[23m?[0m?[3mOOLEAN>?[23m?[0m]
                             Enables Beacon Rest API
                               Default: false
      ?[33m--rest-api-host-allowl?[39m?[0m?[33mist?[39m?[0m[=?[3m<hostname>?[23m?[0m[,?[3m<hostname>?[23m?[0m...]...]
                             Comma-separated list of hostnames to allow, or *
                               to allow any host
                               Default: [127.0.0.1, localhost]
      ?[33m--rest-api-interface?[39m?[0m=?[3m<?[23m?[0m?[3mNETWORK>?[23m?[0m
                             Interface of Beacon Rest API
                               Default: 127.0.0.1
      ?[33m--rest-api-port?[39m?[0m=?[3m<INTEG?[23m?[0m?[3mER>?[23m?[0m
                             Port number of Beacon Rest API
                               Default: 5051
  ?[33m-V?[39m?[0m, ?[33m--version?[39m?[0m              Print version information and exit.
      ?[33m--validator-keys?[39m?[0m=?[3m<KEY_?[23m?[0m?[3mDIR>:<PASS_DIR> | <KEY_FILE>:<PASS_FILE>?[23m?[0m[,?[3m<KEY_DIR>:?[23m?[0m
     ?[3m   <PASS_DIR> | <KEY_FI?[23m?[0m?[3mLE>:<PASS_FILE>?[23m?[0m...]...
                             <KEY_DIR>:<PASS_DIR> will find <KEY_DIR>/**.json,
                               and expect to find <PASS_DIR>/**.txt.
                             <KEY_FILE>:<PASS_FILE> will expect that the file
                               <KEY_FILE> exists, and the file containing the
                               password for it is <PASS_FILE>.
                             The path separator is operating system dependent,
                               and should be ';' in windows rather than ':'.
                               Default: []
      ?[33m--validators-early-att?[39m?[0m?[33mestations-enabled?[39m?[0m[=?[3m<BOOLEAN>?[23m?[0m]
                             Generate attestations as soon as a block is known,
                               rather than delaying until the attestation is due
                               Default: true
      ?[33m--validators-external-?[39m?[0m?[33msigner-keystore?[39m?[0m=?[3m<FILE>?[23m?[0m
                             Keystore (PKCS12/JKS) to use for TLS mutual
                               authentication with external signer
      ?[33m--validators-external-?[39m?[0m?[33msigner-keystore-password-file?[39m?[0m=?[3m<FILE>?[23m?[0m
                             Password file to decrypt keystore (PKCS12/JKS)
                               that will be used for TLS mutual authentication
                               with external signer
      ?[33m--validators-external-?[39m?[0m?[33msigner-public-keys?[39m?[0m[=?[3m<STRINGS>?[23m?[0m[,?[3m<STRINGS>?[23m?[0m...]...]
                             The list of external signer public keys, or a URL
                               to load the keys from
                               Default: []
      ?[33m--validators-external-?[39m?[0m?[33msigner-slashing-protection-enabled?[39m?[0m[=?[3m<BOOLEAN>?[23m?[0m]
                             Enable internal slashing protection for external
                               signers
                               Default: true
      ?[33m--validators-external-?[39m?[0m?[33msigner-timeout?[39m?[0m=?[3m<INTEGER>?[23m?[0m
                             Timeout (in milliseconds) for the external signing
                               service
                               Default: 5000
      ?[33m--validators-external-?[39m?[0m?[33msigner-truststore?[39m?[0m=?[3m<FILE>?[23m?[0m
                             Keystore (PKCS12/JKS) to trust external signer's
                               self-signed certificate
      ?[33m--validators-external-?[39m?[0m?[33msigner-truststore-password-file?[39m?[0m=?[3m<FILE>?[23m?[0m
                             Password file to decrypt keystore (PKCS12/JKS)
                               that will be used to trust external signer's
                               self-signed certificate
      ?[33m--validators-external-?[39m?[0m?[33msigner-url?[39m?[0m=?[3m<NETWORK>?[23m?[0m
                             URL for the external signing service
      ?[33m--validators-graffiti?[39m?[0m=?[3m<GRAFFITI STRING>?[23m?[0m
                             Graffiti value to include during block creation.
                               Value gets converted to bytes and padded to
                               Bytes32.
      ?[33m--validators-graffiti-?[39m?[0m?[33mfile?[39m?[0m=?[3m<GRAFFITI FILE>?[23m?[0m
                             File to load graffiti value to include during
                               block creation. Value gets converted to bytes
                               and padded to Bytes32. Takes precedence over
                               --validators-graffiti. If the file can not be
                               read, the --validators-graffiti value is used as
                               a fallback.
      ?[33m--validators-keystore-?[39m?[0m?[33mlocking-enabled?[39m?[0m=?[3m<BOOLEAN>?[23m?[0m
                             Enable locking validator keystore files
                               Default: true
      ?[33m--validators-performan?[39m?[0m?[33mce-tracking-mode?[39m?[0m=?[3m<TRACKING_MODE>?[23m?[0m
                             Set strategy for handling performance tracking.
                               Valid values: LOGGING, METRICS, ALL, NONE
                               Default: ALL
      ?[33m--ws-checkpoint?[39m?[0m=?[3m<STRIN?[23m?[0m?[3mG>?[23m?[0m
                             A recent checkpoint within the weak subjectivity
                               period. Should be a string containing
                               <BLOCK_ROOT>:<EPOCH_NUMBER> or a URL containing
                               the field ws_checkpoint with the same
                               information.
Commands:
  ?[1mhelp?[21m?[0m                  Displays help information about the specified command
  ?[1madmin?[21m?[0m                 Holds advanced tools for node admins
  ?[1mtransition?[21m?[0m            Manually run state transitions
  ?[1mpeer?[21m?[0m                  Commands for LibP2P PeerID
  ?[1mgenesis?[21m?[0m               Commands for generating genesis state
  ?[1mslashing-protection?[21m?[0m   Manage local slashing protection data used by the
                          validator client.
  ?[1mmigrate-database?[21m?[0m      Migrate the database to a specified version.
  ?[1mdebug-tools?[21m?[0m           Utilities for debugging issues
  ?[1mvalidator-client?[21m?[0m, ?[1mvc?[21m?[0m  Run a Validator Client that connects to a remote Beacon
                          Node
  ?[1mvoluntary-exit?[21m?[0m        Create and sign a voluntary exit for a specified
                          validator.

Teku is licensed under the Apache License 2.0
">
to contain:
 <"-n, --network=<NETWORK>    Represents which network to use.
                               Default: mainnet"> 
	at tech.pegasys.teku.cli.options.Eth2P2PNetworkOptionsTest.helpDisplaysDefaultNetwork(Eth2P2PNetworkOptionsTest.java:134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:212)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:208)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by jeyakatsa** [comment]
I'm reading through all this and it seems like some variables/commands need to be changed within the _Eth2P2PNetworkOptionsTest_ class (at least according to the failed test results) [currently perusing through all this].

**Comment by ajsutton** [comment]
ah that's interesting.  It looks like colour output has somehow wound up enabled when the test prints the help text so it then isn't finding the expected string (because the actual string has a bunch of control characters in it to set the colours). I'm not sure why that's happening - it obviously thinks it's attached to a console in your setup whereas it usually doesn't.

**Comment by jeyakatsa** [comment]
I'm suspecting it's the terminal I'm using (Gitbash), I'll try using my Ubuntu terminal. It could also be the Java version I have installed: 11.0.12

I'm running through all the possibilities and I'll get back with the results.

**Comment by ajsutton** [comment]
@jeyakatsa Give it a try with the changes in https://github.com/ConsenSys/teku/pull/4578 - it hopefully overrides PicoCLI's console detection to force colours to be disabled which should get the test to pass for you.

**Comment by jeyakatsa** [comment]
@ajsutton that resolved it. The Gradle build completed successfully, but there are still dependency import issues when opening the client through Eclipse. Can I at least build some of the Light Client Api infrastructure while some of the Teku dependencies are in red?  

I'm suspecting I can (since the Gradle build was successful [regardless of the dependency import issues appearing in red through Eclipse]).

**Comment by jeyakatsa** [comment]
Just an FYI (I've started building the PublicKey Getters and Setters into the Light Client infrastructure). Will be opening a pull request once I test the said and possibly other functionalities against Gradle. 

Thanks again Aj.

**Pull request closed without merging**
