### PR TITLE
Trusted setup cli option for genesis mock subcommand

### PR DESCRIPTION
**Pull request by usmansaleem**
## PR Description
Genesis mock subcommand allows to specify custom network file to generate mock genesis file for interop testing. Similar to main teku command, this subcommand also need `--Xtrusted-setup` to override trusted setup file when used in conjunction to custom network file (otherwise this subcommand throws error). 

Sample usage:
```
$TEKU_HOME/bin/teku genesis mock --Xtrusted-setup=teku/minimal-trusted-setup.txt --output-file teku-custom.ssz --network teku/config.yaml --validator-count 256 --genesis-time 1695688184
```

## Documentation

- [x] I thought about documentation and added the `doc-change-required` label to this PR if updates are required.

## Changelog

- [x] I thought about adding a changelog entry, and added one if I deemed necessary.

### CODE REVIEW

**Comment by tbenr** [comment]
@usmansaleem I cannot replicate the issue. Maybe there is something in the network config that triggers it. Can you share the file you are using?

**Comment by usmansaleem** [comment]
@tbenr https://github.com/usmansaleem/beku/blob/main/teku/config.yaml would cause the issue.

**Comment by tbenr** [comment]
@usmansaleem we are going to a different direction: ignoring kzg config when it isn't needed. We recently merged a PR about this but there was a bug. I added a fix via #7550

**Comment by usmansaleem** [comment]
> @usmansaleem we are going to a different direction: ignoring kzg config when it isn't needed. We recently merged a PR about this but there was a bug. I added a fix via #7550

Makes sense, I'll close my PR.

**Pull request closed without merging**
